// <auto-generated />
using GranjaGraphQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GranjaGraphQL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241211000030_InitialCreatSs")]
    partial class InitialCreatSs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GranjaGraphQL.Models.Alimentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PorcinoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PorcinoId");

                    b.ToTable("Alimentaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detalles = "Alimentación balanceada con proteínas",
                            PorcinoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Detalles = "Alimentación con maíz y soja",
                            PorcinoId = 2
                        });
                });

            modelBuilder.Entity("GranjaGraphQL.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Pérez",
                            Cedula = "1234567890",
                            Direccion = "Calle Falsa 123",
                            Nombres = "Juan",
                            Telefono = "555-1234"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Gómez",
                            Cedula = "0987654321",
                            Direccion = "Calle Verdadera 456",
                            Nombres = "Ana",
                            Telefono = "555-5678"
                        });
                });

            modelBuilder.Entity("GranjaGraphQL.Models.Porcino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<string>("Raza")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Porcinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            Edad = 2,
                            Identificacion = "P001",
                            Peso = 120.5f,
                            Raza = "Landrace"
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            Edad = 3,
                            Identificacion = "P002",
                            Peso = 150.2f,
                            Raza = "Duroc"
                        });
                });

            modelBuilder.Entity("GranjaGraphQL.Models.Alimentacion", b =>
                {
                    b.HasOne("GranjaGraphQL.Models.Porcino", "Porcino")
                        .WithMany("Alimentaciones")
                        .HasForeignKey("PorcinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Porcino");
                });

            modelBuilder.Entity("GranjaGraphQL.Models.Porcino", b =>
                {
                    b.HasOne("GranjaGraphQL.Models.Cliente", "Cliente")
                        .WithMany("Porcinos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GranjaGraphQL.Models.Cliente", b =>
                {
                    b.Navigation("Porcinos");
                });

            modelBuilder.Entity("GranjaGraphQL.Models.Porcino", b =>
                {
                    b.Navigation("Alimentaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
